package android.example.farmer.source;

public class ProductionEntry {
    private int firstProduction;
    private int secondProduction;
    private int thirdProduction;
    private int totalProduction;


    private int firstCrackedEggs;
    private int firstGoodEggs;
    private int secondCrackedEggs;
    private int secondGoodEggs;
    private int thirdCrackedEggs;
    private int thirdGoodEggs;
    private String productionDate;



    private String penName;

    /**
     * This constructor is for adding a new entry to the database. Id is autogenerated so is not needed
     * in this constructor
     *
     * @param firstProduction
     * @param secondProduction
     * @param thirdProduction
     * @param totalProduction
     * @param firstCrackedEggs
     * @param firstGoodEggs
     * @param secondCrackedEggs
     * @param secondGoodEggs
     * @param thirdCrackedEggs
     * @param thirdGoodEggs
     */
    public ProductionEntry(String penName,int firstProduction, int secondProduction, int thirdProduction, int totalProduction
            , int firstCrackedEggs, int firstGoodEggs, int secondCrackedEggs, int secondGoodEggs,
                           int thirdCrackedEggs, int thirdGoodEggs, String productionDate) {
        this.firstProduction = firstProduction;
        this.secondProduction = secondProduction;
        this.thirdProduction = thirdProduction;
        this.totalProduction = totalProduction;
        this.firstCrackedEggs = firstCrackedEggs;
        this.firstGoodEggs = firstGoodEggs;
        this.secondCrackedEggs = secondCrackedEggs;
        this.secondGoodEggs = secondGoodEggs;
        this.thirdCrackedEggs = thirdCrackedEggs;
        this.thirdGoodEggs = thirdGoodEggs;
        this.productionDate = productionDate;
        this.penName=penName;
    }

    public ProductionEntry() {
    }

    public String getPenName() {
        return penName;
    }

    public void setPenName(String penName) {
        this.penName = penName;
    }

    public int getFirstProduction() {
        return firstProduction;
    }

    public void setFirstProduction(int firstProduction) {
        this.firstProduction = firstProduction;
    }

    public int getSecondProduction() {
        return secondProduction;
    }

    public void setSecondProduction(int secondProduction) {
        this.secondProduction = secondProduction;
    }

    public int getThirdProduction() {
        return thirdProduction;
    }

    public void setThirdProduction(int thirdProduction) {
        this.thirdProduction = thirdProduction;
    }

    public int getTotalProduction() {
        return totalProduction;
    }

    public void setTotalProduction(int totalProduction) {
        this.totalProduction = totalProduction;
    }

    public int getFirstCrackedEggs() {
        return firstCrackedEggs;
    }

    public void setFirstCrackedEggs(int firstCrackedEggs) {
        this.firstCrackedEggs = firstCrackedEggs;
    }

    public int getFirstGoodEggs() {
        return firstGoodEggs;
    }

    public void setFirstGoodEggs(int firstGoodEggs) {
        this.firstGoodEggs = firstGoodEggs;
    }

    public int getSecondCrackedEggs() {
        return secondCrackedEggs;
    }

    public void setSecondCrackedEggs(int secondCrackedEggs) {
        this.secondCrackedEggs = secondCrackedEggs;
    }

    public int getSecondGoodEggs() {
        return secondGoodEggs;
    }

    public void setSecondGoodEggs(int secondGoodEggs) {
        this.secondGoodEggs = secondGoodEggs;
    }

    public int getThirdCrackedEggs() {
        return thirdCrackedEggs;
    }

    public void setThirdCrackedEggs(int thirdCrackedEggs) {
        this.thirdCrackedEggs = thirdCrackedEggs;
    }

    public int getThirdGoodEggs() {
        return thirdGoodEggs;
    }

    public void setThirdGoodEggs(int thirdGoodEggs) {
        this.thirdGoodEggs = thirdGoodEggs;
    }

    public String getProductionDate() {
        return productionDate;
    }

    public void setProductionDate(String productionDate) {
        this.productionDate = productionDate;
    }
}
